version: '3.8'
services:
  gateway:
    build: ./services/gateway
    ports: ['3000:3000']
    depends_on: [redis, postgres, auth, catalog]
    environment:
      - NODE_ENV=development
  auth:
    build: ./services/auth
    ports: ['4000:4000']
  catalog:
    build: ./services/catalog
    ports: ['5000:5000']
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: catalog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      RUN_MIGRATIONS: 'true'
      NODE_ENV: development
    depends_on: [postgres]
  redis:
    image: redis:alpine
    ports: ['6379:6379']
  postgres:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: catalog
    ports: ['5432:5432']
    volumes:
      - postgres_data:/var/lib/postgresql/data
  orders:
    build: ./services/orders
    ports: ['6000:6000']
    environment:
      NODE_ENV: development
    depends_on: [postgres]
  commission:
    build: ./services/commission
    ports: ['7000:7000']
    environment:
      NODE_ENV: development

volumes:
  postgres_data:
