services:
  - type: web
    name: publica-viagens-tfd
    env: node
    buildCommand: npm run render:build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: 1
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /
    autoDeploy: true