name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          node-version: 18
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm tsc --noEmit
      - run: pnpm test
      - run: pnpm build --filter services/gateway
      - name: Build Docker images
        run: |
          docker build -t myorg/gateway:pr-${{ github.event.number }} services/gateway
          docker build -t myorg/pocketbase:pr-${{ github.event.number }} services/pocketbase
